### ISSUE TITLE
What's your version for opencv-python?

### ISSUE THREAD

**Issue by yaoshanliang** [BerensRWU/Complex_YOLO#2]
I installed opencv 4.5.3 and  got the following error.

cv2.error: OpenCV(4.5.3) :-1: error: (-5:Bad argument) in function 'line'
> Overload resolution failed:
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type

**Comment by BerensRWU** [comment]
Hello I have tested it with version 4.1.1.
